data:
  path: . # files must be called x_train, x_test, y_train, y_test in the data path
  file_type: .npy
  img: brightfield # choices for this option include "nucleus", "actin", "brightfield" or "all"
  num_classes: 5

model:
  name: small # names are small, mobilenet and autoencoder
  output: classification # choices are classification or regression - if autoencoder, this value does not matter
  filter_dim: [3, 3]
  epochs: 50
  batch_size: 64
